---
count: 4
default:
  restart: 0
  wait: 0
editor:
  files:
    eg:
      - some-file.eg
name: Group-Git-Taggers-Ruby
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2:
      edit: lib
  3: []

  4: []

